server:
  port: 8888
spring:
  application:
    name: hapicker-cloud-configer
  cloud:
    config:  # git管理配置
      server:
        git:
          uri: your_uri  #配置git仓库位置
          search-paths: conf
          label: master
          username: your_username
          password: your_password

##注册中心
#eureka:
#  client:
#    service-url:
#      defaultZone: http://111.231.83.73:21888/eureka/


# http://127.0.0.1:6018/application/dev




