server:
  port: 6018
spring:
  application:
    name: hapicker-cloud-configer
  cloud:
    config:  # git管理配置
      server:
        git:
          uri: https://gitee.com/mryyf/hapicker-cloud-configer  #配置git仓库位置
          search-paths: conf
          label: master
          username: 416530244@qq.com
          password: yyf1238523

##注册中心
#eureka:
#  client:
#    service-url:
#      defaultZone: http://111.231.83.73:21888/eureka/


# http://127.0.0.1:6018/application/dev



# Spring Cloud Config也提供本地存储配置的方式。我们只需要设置属性
# spring.profiles.active=native，Config Server会默认从应用的src/main/resource目录下检索配置文件。
# 也可以通过spring.cloud.config.server.native.searchLocations=file:F:/properties/属性来指定配置文件的位置。
# 虽然Spring Cloud Config提供了这样的功能，但是为了支持更好的管理内容和版本控制的功能，还是推荐使用git的方式。
