server:
  port: 6018
spring:
  application:
    name: hapicker-cloud-configer
  cloud:
    config:  # git管理配置
      server:
        git:
          uri: https://gitee.com/mryyf/hapicker-cloud-configer  #配置git仓库位置
          search-paths: conf
          label: master
          username: 416530244@qq.com
          password: yyf1238523

##注册中心
#eureka:
#  client:
#    service-url:
#      defaultZone: http://111.231.83.73:21888/eureka/


# http://127.0.0.1:6018/application/dev




